### ISSUE TITLE
onclick event on the drop instance?

### ISSUE THREAD

**Issue by dandv** [HubSpot/drop#101]
Similar to #62, I was trying to get a "click" event to fire when the user clicks on a drop. Don't think that's the intended purpose of `on` though.

http://codepen.io/dandv/pen/QbVdeW

Would this be a useful feature to add? If not, what is the recommended patter for handling clicks on the drop? `drop.content.addEventListener`?

**Comment by geekjuice** [comment]
IIRC, the way I usually handle click events in the drop element is to add/remove listeners during the `open` and `close` events respectively. 

```javascript
var element = document.querySelector('#element');

drop.on('open', function (event) {
  element.addEventListener('click', cb);
});

drop.on('close', function (event) {
  element.removeEventListener('click', cb);
});
```

**Comment by geekjuice** [comment]
Closing for now. Feel free to reopen if the above doesn't solve the issue.
