### ISSUE TITLE
Support for IE9

### ISSUE THREAD

**Issue by DhrubaRC** [HubSpot/drop#102]
Hello,
Can anyone please confirm if the latest version of drop has stopped supporting IE9? I was checking couple of examples via Browserstack (https://www.browserstack.com/) when I chanced upon this issue.

Any clarification in this matter will be much appreciated.

Thank you!

**Comment by geekjuice** [comment]
Thanks for the heads up. Are there specific examples in question that have stopped working? If so, would you happen to know what errors they are throwing (don't have a BrowserStack account on me and wanted to ask first). :smiley_cat:

**Comment by MGPalmer** [comment]
![screenshot from 2015-09-30 11 09 35](https://cloud.githubusercontent.com/assets/300129/10188973/ca17b1b0-6763-11e5-9967-8fc77c63bb0b.png)

It seems to not work for me as well :(

**Comment by MGPalmer** [comment]
No errors to be seen in the IE9 console.

**Comment by MGPalmer** [comment]
@geekjuice Hi ! I don't want to appear pushy, but is there any chance this can be fixed soon for IE9 ? I've sent you a private email as well but I'm not sure it went through :/

**Comment by geekjuice** [comment]
@MGPalmer Ah sorry about that. For some reason, your email fell through my inbox into the wrong folder :crying_cat_face:

I can start taking a look right away, but I can't guarantee an ETA of when this may get resolved. However, I've set up a BrowserStack account since my last comment, so I definitely have more tools at my disposal now.

**Comment by MGPalmer** [comment]
@geekjuice This is great news, thanks for taking this up !
Luckily our deadline was extended by a week so it's not quite as urgent anymore for us, but having IE9 work by end of this week would still make our day :)
Also, I'm just using these VMs https://dev.modern.ie/tools/vms/linux/ if that's any help to you.

**Comment by geekjuice** [comment]
So I just realized that we do support IE9. The welcome docs used an older version of Tether that contained a bug that is shown above. It was fixed [here](https://github.com/HubSpot/tether/pull/97). So as long as you use a version of tether great than `1.0.2`, you should be fine.

**Comment by MGPalmer** [comment]
@geekjuice Thanks a lot already :)

However, there still is a problem with the example "The social share" - the list does not close again, neither by clicking or moving the mouse away.

Unfortunately, we're using the same style in our app, and additionally the styles don't seem to be applied, see the screenshot...
![selection_030](https://cloud.githubusercontent.com/assets/300129/10337056/7f575f0a-6cfd-11e5-96a0-96e9fc5f04f0.png)

**Comment by MGPalmer** [comment]
I'm now using:

    rails-assets-tether (1.1.0)
    rails-assets-tether-drop (1.3.0)

via rails-assets.

**Comment by MGPalmer** [comment]
Whups, added a new ticket in #115

**Comment by geekjuice** [comment]
So initial my gut told me this was probably due to some issue with the `transitionend` event not being supported in IE9. And it seemed like my gut was right... :disappointed:

Basically, the `drop-open-transitionend` class (which we suggest to use to handle showing the content via `display: block`) is not being removed since it listens for the `transitionend` event to remove it.

There are few things we could consider to work araound this for IE9. The easiest may be to alter the CSS itself to not rely on the `drop-open-transitionend` event and possibly use transition delays instead to toggle styles like `visibility`, `display`, and `opacity`.

The other solution is could be that we could include a `transitionend` polyfill such as [transitionEnd](https://github.com/EvandroLG/transitionEnd) or at least provide a fallback to it and ask the end-user to include it if they need support for IE9.

**Comment by MGPalmer** [comment]
I'm afraid I don't know enough about frontend development or IE9 quirks to have an informed opinion in this case :)

I can offer another observation if that helps - I played around with the themes in case I got something wrong there and it seems that when I set no "classes" at all when instantiating a Drop in the JS, all browsers have the same behaviour as in IE9 (no styles, don't close).

**Comment by geekjuice** [comment]
Could you try using one of the non-transitional themes like `drop-theme-basic`? I'm fairly sure that as long as the theme has no transitions (or does not depend on `drop-open-transitionend`), the behavior should be the same starting from IE9

**Comment by MGPalmer** [comment]
I am using that :(

**Comment by MGPalmer** [comment]
I'll post an example of what I'm doing in a minute..

**Comment by MGPalmer** [comment]
```
<link href="/assets/tether-drop/dist/css/drop-theme-basic.css?body=1" media="screen" rel="stylesheet" type="text/css" />
```

contents of that:

```
/* line 1, ../../../../../../../../.rvm/gems/ruby-2.2.2/gems/rails-assets-tether-drop-1.3.0/app/assets/stylesheets/tether-drop/dist/css/drop-theme-basic.scss */
.drop-element, .drop-element:after, .drop-element:before, .drop-element *, .drop-element *:after, .drop-element *:before {
  box-sizing: border-box;
}

/* line 4, ../../../../../../../../.rvm/gems/ruby-2.2.2/gems/rails-assets-tether-drop-1.3.0/app/assets/stylesheets/tether-drop/dist/css/drop-theme-basic.scss */
.drop-element {
  position: absolute;
  display: none;
}

/* line 7, ../../../../../../../../.rvm/gems/ruby-2.2.2/gems/rails-assets-tether-drop-1.3.0/app/assets/stylesheets/tether-drop/dist/css/drop-theme-basic.scss */
.drop-element.drop-open {
  display: block;
}

/* line 10, ../../../../../../../../.rvm/gems/ruby-2.2.2/gems/rails-assets-tether-drop-1.3.0/app/assets/stylesheets/tether-drop/dist/css/drop-theme-basic.scss */
.drop-element.drop-theme-basic {
  max-width: 100%;
  max-height: 100%;
}

/* line 13, ../../../../../../../../.rvm/gems/ruby-2.2.2/gems/rails-assets-tether-drop-1.3.0/app/assets/stylesheets/tether-drop/dist/css/drop-theme-basic.scss */
.drop-element.drop-theme-basic .drop-content {
  border-radius: 5px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
  font-family: inherit;
  background: #eee;
  color: #444;
  padding: 1em;
  font-size: 1.1em;
  line-height: 1.5em;
}
```

markup, redacted a little:

```
<div class='col actions'>
  <a href="#" class="payload-action-button" data-payload-action-menu-id="page-action-menu-729">Actions</a>
  <ul class='payload-action-menu' id='page-action-menu-729'>
    <li class='payload-action-menu-item'>
      <a href="/admin/en/directory/pages/preview?id=729" class="payload-action-menu-item-link payload-action-menu-item-preview preview">Preview</a>
    </li>
  </ul>
</div>
```


JS:

```
$(document).ready(function() {
  
  $.each($('.payload-action-button'), function( index, button ) {
    var selector = ("#" + $(button).data("payload-action-menu-id"));
    new Drop({
      target: button,
      content: document.querySelector(selector),
      position: 'bottom left',
      openOn: 'click',
      classes: 'drop-theme-basic'
    });
  });
});
```

**Comment by geekjuice** [comment]
We can continue this in https://github.com/HubSpot/drop/issues/115
