### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by makketagg** [HubSpot/drop#105]
Hello, everyone. I have some problems with Safari support. For example, range input on demo page:
![2015-08-03 14 32 49](https://cloud.githubusercontent.com/assets/4987610/9036759/06cf3e4c-39ed-11e5-81c0-039d9cb62fb8.png)
Safari version - 7.1.7 (9537.85.16.12).

**Comment by geekjuice** [comment]
Quick question, what problem am I observing above? It seems like `drop` is working correctly.

**Comment by mike-post** [comment]
What you're seeing above is that the slider bar is the same color as the background.  (I first viewed the demo in Safari and thought it was supposed to be a dot; later I tried Chrome and realized it was a slider.)

Also, the List Flyout example doesn't work in Safari at all.

No Safari support = non-starter

**Comment by geekjuice** [comment]
@mike-post Ah haha. Never occurred to me that the default slider background is black on safari. We can probably fix that in the themes so it's more browser friendly.

Regarding the `List Flyout` example, which version Safari are you observing this in? I haven't noticed an issue with any of the examples in Safari yet (just trying to gauge if these are issues with the library or specific versions of Safari with known issues with `Drop`)

**Comment by mike-post** [comment]
I'm using Safari 8.0.8. When I click the List Flyout example in Safari, nothing happens. There's also nothing in the console. Altogether, not really even worth a screenshot.

**Comment by geekjuice** [comment]
:crying_cat_face: I was using the same version. Are you using Safari on a Mac or different OS? I've been using Mac so maybe the behavior is different on another OS.

**Comment by mike-post** [comment]
Ah, I've tracked it down: I'm running Safari 8 on OS X 10.10.5.  However, I have v1.9.2 of the [AdBlock Plus](https://adblockplus.org) extension installed. Disabling that extension allows Drop to work as expected (although the slider bar is still the same color as the background).

**Comment by geekjuice** [comment]
Awesome. I'm curious as to why that version of AdBlock would prevent the drop from rendering correctly :confused:

I'll close this for now though, but feel free to open a new issue regarding the AdBlock if it's something you notice with other versions as well. :+1:
