### ISSUE TITLE
Drop.js + FastClick

### ISSUE THREAD

**Issue by sjelfull** [HubSpot/drop#110]
Hi, i'm trying to use Drop.js + FastClick on a button with ```<b>```tag within it.

It seems FastClick (?) is causing a double-click somehow in Safari on iOS8.

Anyone know how to work with Fastclick + Drop.js?

**Comment by geekjuice** [comment]
Hmm, I've personally hadn't look at FastClick before so I can't answer off the top of my head. Would you happen to have an example project that uses FastClick and Drop that I could possible run locally and test?

**Comment by geekjuice** [comment]
Seems like this is related to https://github.com/HubSpot/drop/issues/116, so closing in favor of continuing discussion there.
