### ISSUE TITLE
Dynamically change "target" of Drop

### ISSUE THREAD

**Issue by dmackerman** [HubSpot/drop#112]
First off, fantastic library. It's been a huge convenience.

I think I have a fairly unique scenario, where I'm building a "wizard" of sorts. I have an array of objects which define my "steps". Each step has a `selector` which works beatifully, and for each step, I create a `Drop` instance. I open and close them manually and all is well.

The rub is that some of these `selector`'s aren't available when the DOM first loads, due to the dynamic nature of the the way we want the wizard to work. I figured a nice solution for getting around this would be to define some of the steps as `async`, and then dynamically assign the `target` on the `Drop` instances when the time comes. 

If `async` is true on the step, I default the target to `document.querySelector('body')` so I can change it later.

Some code looks like:

``` js
if (popover.options.async) {
    popover.options.target = $(`[data-wizard-step='${popover.options.selector}']`)[0];
    popover.position();
}

popover.open();
```

The DOM node gets targeted properly, but it appears that `position()` doesn't do anything, and the call to `open()` doesn't open the drop. The drop does actually get rendered in the DOM, but the positioning is wrong. It appears it's still using the `body` query selector that I'm trying to override.

Is dynamic "re-targeting" a supported feature?

Thanks again!

**Comment by geekjuice** [comment]
Thanks for using and supporting __Drop__!

At the moment, I don't believe we support dynamic _re-targeting_, but it also seems like your use case for __Drop__ may be better handled using our __[Shepherd](https://github.com/HubSpot/shepherd)__ library which is designed for tours and wizards.

In fact, we just added support for [conditionally showing steps](https://github.com/HubSpot/shepherd/pull/78) to handle cases like this where an element may not be on the page when a tour is set up. Could your use case be handled using __Shepherd__ instead? :smiley_cat:

**Comment by dmackerman** [comment]
Oh, nice! I've put some significant work into our solution already, but now may have to switch. :rage:

**Comment by geekjuice** [comment]
:sweat_smile: One solution could be flag via `data-attributes` or `classNames` if an element has been `"dropped"`, otherwise setup the `drop` instance at runtime rather than instantiating all the `drop` earlier. Of course, this may be dependent on how your code is structured. For example:

```javascript
const drops = {};

const {dropId} = element.dataset;
if (!dropId) {
  drops[dropId] = new Drop({
    target: element,
    ...
  });
}

drops[dropId].open();
```

**Comment by dmackerman** [comment]
Yeah, good idea. I looked at the code and realized that `position()` just calls Tether's position, which does support "re-targetting" AFAIK. Is that correct?

**Comment by geekjuice** [comment]
I guess that is true. It could be possible to move some of the code around so if the target changes (or some method e.g. `updateTarget` is called), it basically re-constructs the `drop` instance with the previous options cached. Let me think about it for a bit, but if you'd like to get a jump start, I'd be more than happy to review any pull-requests for this feature.
