### ISSUE TITLE
Dropdown-style menu not closing in IE9

### ISSUE THREAD

**Issue by MGPalmer** [HubSpot/drop#115]
Followup to #102 :)

There is a problem with the example "The social share" on http://github.hubspot.com/drop/docs/welcome/ - the list does not close again, neither by clicking or moving the mouse away.

Unfortunately, we're using the same style in our app, and additionally the styles don't seem to be applied, see the screenshot...
![selection_030](https://cloud.githubusercontent.com/assets/300129/10337056/7f575f0a-6cfd-11e5-96a0-96e9fc5f04f0.png)

Using:

    rails-assets-tether (1.1.0)
    rails-assets-tether-drop (1.3.0)

via rails-assets.

**Comment by geekjuice** [comment]
So I input the code from #102 into jsFiddle and ran it in IE9 and it seemed to work as expected. [[jsFiddle]](http://jsfiddle.net/y09m7w7o/2/). Can you confirm if the fiddle works in IE9 for you?

**Comment by MGPalmer** [comment]
Aha ! Yes it works in my IE9...so something in our styles is breaking this, I guess ?

**Comment by geekjuice** [comment]
That would be my guess, although it's hard to say since I can't see the entire code :sweat_smile:. Possible areas to check would be the styles for `.payload-action-menu`. It may also help to grok for styles like that begin with `.drop-` and see if anything is overriding those.

**Comment by MGPalmer** [comment]
Hmmm I remembered about Firebug Lite so I have now at least a little insight into what's happening inside IE.

I also added alert()s to the open and close callbacks in drop.js. It looks like even though both open and close are executed, the drop-open etc. classes are not removed from the drop element.

**Comment by MGPalmer** [comment]
Ok, last note for now - when I use the embedding feature to completely change the class namespace away from "drop-", nothing changes.
 :(
Thanks a lot anyway!

**Comment by geekjuice** [comment]
Could you explain what you mean by embedding feature? At the moment, the class namespace is primarily used for create themes using the SASS files and I don't believe we support changing the namespace yet (unless you changed the actually source file)

**Comment by MGPalmer** [comment]
I used something like this:

```
_Drop = Drop.createContext
  classPrefix: 'funandgames'
```

and instantiated the Drop(s) with classes: 'funandgames', and copied the basic theme and changed all the drop- prefixes to "funandgames-".

The error is still there on IE with that. I thought this would demonstrate that at least it's not some other CSS/JS getting hung up on the drop- classes.

**Comment by geekjuice** [comment]
Ah, ok. Let me play with the fiddle to use a different context like you have above and see if the issue comes up then.

**Comment by MGPalmer** [comment]
Hmm I'm not sure if that'll help with my issue though.

**Comment by geekjuice** [comment]
Could you create a jsFiddle/jsBin/etc reproducing these issues? It's a bit difficult trying to recreate these issues when I can't seem to reproduce them.

**Comment by MGPalmer** [comment]
I can try, but right now I need to deal with other things :/ Probably tomorrow...is it ok for you to let this rest for a bit ?

**Comment by geekjuice** [comment]
Sure not a problem :+1:

**Comment by MGPalmer** [comment]
BTW, can you give an email address with an attached Paypal account ? We'd like to say thank-you :) Best mail it to me to the address I used earlier.

**Comment by MGPalmer** [comment]
Ok, I got it \o/

It was simply the limit to stylesheet files and/or css selectors that IE9 has - the styles simply did not get loaded X( Using the precompiled assets in development, everything works.

**Comment by geekjuice** [comment]
(facepalm) oh IE9... haha glad to hear it (might?) work :+1:

**Comment by MGPalmer** [comment]
It works beautifully now !

**Comment by geekjuice** [comment]
Also, no need to thank me via PayPal :smile_cat:

Contributing to our OS projects is thanks enough :beers:

**Comment by MGPalmer** [comment]
Well, if you insist ;) Then just let me thank you here, you were of tremendous help !
