### ISSUE TITLE
Your documentation is shit.

### ISSUE THREAD

**Issue by xrisk** [HubSpot/drop#119]
Sorry to say it, but this library looked promising. Totally turned off by anything remotely resembling properly documentation. Heck I spent over an hour trying to implement one of the drops in the demo page >.< What a shame.

**Comment by geekjuice** [comment]
Sorry you feel that way. Mind commenting specifically on what was difficult made the [documentation](http://github.hubspot.com/drop/) hard to understand?

**Comment by dubvfan87** [comment]
The documentation is definitely sufficient. You can view the source of the examples page to get some starter ideas on styling.
