### ISSUE TITLE
[Sass] Update style compilation

### ISSUE THREAD

**Issue by geekjuice** [HubSpot/drop#126]
> Maybe remove `bower` all together?

Right now, `drop` styles depends on `bower` packages to be installed to pull in the `tether` Sass mixins. This requires developers to install `tether` through `bower`. It might be better to just use `node_modules` instead and create an opinionated standard when you developing on this project.

**Comment by massimopalmieri** [comment]
Any update on this? Changing the imports from:

```
@import ../bower_components/tether/src/css/helpers/tether
@import ../bower_components/tether/src/css/helpers/tether-theme-arrows
```

to this:

```
@import ../../../tether/src/css/helpers/tether
@import ../../../tether/src/css/helpers/tether-theme-arrows
```

would make it work both on bower and npm3
