### ISSUE TITLE
Drop is not staying in window as specified

### ISSUE THREAD

**Issue by jmeridth** [HubSpot/drop#129]
Issue:
We have a div that is at the top left of our page and when clicked the drop is off the page.

What is happening:
![screen shot 2015-12-03 at 11 38 57 am](https://cloud.githubusercontent.com/assets/35014/11568628/dedad2fe-99b2-11e5-9a7f-c2fbef67f706.png)

What we want:
![screen shot 2015-12-03 at 11 39 15 am](https://cloud.githubusercontent.com/assets/35014/11568618/d3ca54fc-99b2-11e5-87fe-63c3abcc99be.png)

The latter is happening if I add `pin: true` but we don't want pin because we don't want the drop to stay on the screen when we scroll.

Here is what we currently have for code (coffeescript):

```javascript
new Drop
  target: @border.element[0]
  classes: 'te--drop-wrapper drop-theme-arrows'
  remove: true
  openOn: 'click'
  tetherOptions: {
    attachment: 'top center'
    targetAttachment: 'top center'
    constraints: [
      {
        to: 'window'
        attachment: 'together'
      }
    ]
  }
```

Looking at CSS:

```css
<div class="drop te--drop-wrapper drop-theme-arrows drop-element drop-enabled drop-abutted drop-abutted-top drop-element-attached-top drop-element-attached-center drop-target-attached-top drop-target-attached-center drop-open drop-open-transitionend drop-out-of-bounds drop-out-of-bounds-left drop-after-open" style="top: 0px; left: 0px; position: absolute; transform: translateX(-294px) translateY(20px) translateZ(0px);">
```

Please note the `translateX` is a negative value.

Any help is appreciated.

**Comment by geekjuice** [comment]
So this is will probably be resolved once I finally get around to fully testing https://github.com/HubSpot/tether/pull/115. At the moment, `drop` and more accurately, `tether` will only reposition on the y-axis and not the x-axis. If you would like to help out though with getting that other PR merged in sooner, feel free to use that branch version of `tether` with `drop` with the appropriate `tetherOptions` and let me know if that resolves the issue :+1:

**Comment by jmeridth** [comment]
@geekjuice awesome!  I will grab that branch and see what it does.  Thank you for pointing me in that direction.

**Comment by jmeridth** [comment]
@geekjuice your version of tether.js (v1.2.0) didn't solve my issue. Can you double check my` tetherOptions` above are acceptable? I'm testing different combinations.

**Comment by jmeridth** [comment]
@geekjuice removing the entire `tetherOptions` section from our code above makes your v1.2.0 code work.  :tada:  We will give your PR a :+1:  Thank you for the hard work.

**Comment by josephrocca** [comment]
I'm getting a 404 for that link. Has there been any progress on this? Can someone point me to a build that fixes the horisontal out-of-viewport positioning? @jmeridth @geekjuice Would be very much appreciated! Cheers

**Comment by jmeridth** [comment]
@josephrocca @geekjuice got the fix into 1.2.1 I believe.  That branch was merged in #115 and the tether.js there (https://github.com/HubSpot/tether/commit/94ea792b2441905f66e7ff8f080ca91db04154a3) had his fix.  I'm not personally using drop anymore but @geekjuice can probably confirm it hasn't regressed in any way. /cc @huoxito

**Comment by jmeridth** [comment]
Closing this since I opened it and #115 code fixed it for us when needed.  Thanks @geekjuice

**Comment by josephrocca** [comment]
Thanks @jmeridth! Can you confirm that it was fixed in 1.2.1 geekjuice? I've tried all of the latest versions to no avail, but if it was merged, and it worked for jmeridth, then it's likely something I'm doing wrong. Any special options need to be passed in? Here's my constuctor:

```
        var dropInstance = new Drop({
          target: e.target,
          content: "...",
          position: 'top center',
          openOn: 'always',
          classes: "drop-theme-arrows-bounce-dark",
          remove: true
        });
```

Thanks

**Comment by jmeridth** [comment]
@josephrocca as I'm not working on that project anymore, I can't verify.  My suggestion is remove `content` and `position` as they weren't in my original post example.  See if that works.  And when you add them back it fails, may need a new issue.  At one point I tried all of the combinatorics and came to the conclusion we had to remove the whole `tetherOptions` section to get it to work for us.  Hope this helps.  Cheers.

**Comment by huoxito** [comment]
we've been using the patch mentioned above for a while now and it's working great, this is how we create drop instances for the record:

``` js
    new Drop(
      target: target,
      remove: true,
      openOn: 'click',
      tetherOptions: {
        attachment: 'top center',
        targetAttachment: 'bottom center',
        constraints: [
          {
            to: 'window',
            attachment: 'both'
          }
        ]
      }
    )
```

I believe you can set attachment and targetAttachment to any valid option and it should still work

**Comment by josephrocca** [comment]
Thanks a lot, both of you! Seems that I just needed to get rid of the `position` option - should have guessed that, given that I wanted the positioning to be dynamic...

I also had include your `tetherOptions`, huoxito, otherwise it was acting a bit weird.

Thanks again!

And for reference, here is my new constructor:

```
        var dropInstance = new Drop({
          target: e.target,
          content: "...",
          openOn: 'always',
          classes: "drop-theme-arrows-bounce-dark",
          remove: true,
          tetherOptions: {
            attachment: 'top center',
            targetAttachment: 'bottom center',
            constraints: [
              {
                to: 'window',
                attachment: 'both'
              }
            ]
          },
        });
```
