### ISSUE TITLE
Contributing documentation

### ISSUE THREAD

**Issue by altearius** [HubSpot/drop#137]
I recently forked this project and got it working locally.  The contributing documentation says:

> Run `npm install` to install both node modules and bower components

Alas, this only installed node modules for me.  I had to run `bower install` separately before I could run `npm run build`.

Am I missing something, or should the documentation be updated?

**Comment by geekjuice** [comment]
Ah, the documentation needs to be updated. The `post-install` script that would run `bower install` was removed in [this commit](https://github.com/HubSpot/drop/commit/5cdf4a300c4488928cde9307b50acca0bf47c4ea). 

Thanks for the catching that!
