### ISSUE TITLE
Drop popup doesn't close when I end hover if my mouse is within the drop element.

### ISSUE THREAD

**Issue by Lugghawk** [HubSpot/drop#150]
My use case is a grid of items that I'd like to have a hover-triggered drop appear over (one on each item). However in any position I place the drop it will likely be completely covering another grid item (that has its own drop which is currently hidden).

When moving my mouse off the drop-target element, but into the drop-content element (and over the grid item behind it), the drop element remains on the screen, while I'd like it to disappear so my other grid items' drop-content elements can appear.

**Comment by geekjuice** [comment]
While its use is debatable, you can use `pointer-events: none` to prevent the drop from remaining on hover. This is how we prevent popovers from lingering in [HubSpot/tooltip](https://github.com/HubSpot/tooltip/blob/master/src/css/tooltip-theme-arrows.sass#L18).

**Comment by Lugghawk** [comment]
Thanks.
