### ISSUE TITLE
Error is thrown if drop is destroyed before hover timeout executes

### ISSUE THREAD

**Issue by zmdavis** [HubSpot/drop#169]
1. Create a drop that opens on hover with a hoverOpenDelay
2. Hover over target, which sets a timeout
3. Destroy the drop (before timeout executes)
4. Timeout is not cleared, and when it executes a js error is thrown

The actual error thrown is `Cannot read property 'parentNode' of null` and is caused by https://github.com/HubSpot/drop/blob/master/src/js/drop.js#L374

If `this.drop` is null when `open` is called it should probably just return instead of trying to do things.

**Comment by streamside** [comment]
Looks like a duplicate of #139.

**Comment by zmdavis** [comment]
Indeed. Sorry about that, I only looked for existing open issues, not open PRs.
