### ISSUE TITLE
CSS, filter not supported by Firefox, leads to no outline in theme-arrow-bounce

### ISSUE THREAD

**Issue by zischwartz** [HubSpot/drop#24]
In `drop-theme-arrow-bounce`

    -moz-filter: drop-shadow(0 1px 4px rgba(0, 0, 0, 0.2));

Doesn't work, because [Firefox doesn't fully support filter yet](https://developer.mozilla.org/en-US/docs/Web/CSS/filter#Gecko_notes). So you end up with no outline around the Drop, which is confusing (but not a huge deal).

**Comment by geekjuice** [comment]
Good point. As a workaround, I would suggest adding custom styles if you need to fully support Firefox. You could augment the styles with `box-shadow` on `.drop-content`, but keep in mind that it will not produce a shadow under the arrow (as arrow is created using `border`).
