### ISSUE TITLE
UsingThe Example file

### ISSUE THREAD

**Issue by SlyOne** [HubSpot/drop#26]
Using the example file index.html 
1> all links are broken.,it needs to be at root level.
2> my interest was in the List flyout. How can use this with unknown number between 2-25. and can it be nested? 
3> how do get it to show only below the clicked box, right now it jumps above and below on scroll.

Thanks

**Comment by geekjuice** [comment]
1. My guess was you were trying to open `index.html` from just within the project. I'm fairly sure those files are primarily for the documentation pages and require additional build steps to run locally.

2. The animations for the __List Flyout__ are not actually a feature of `Drop`, rather styles that the creators of `Drop` added for the documentation. That's outside of the scope of this project, but the source can be found [here](https://github.com/HubSpot/drop/blob/master/docs/welcome/examples/social-sharing/sass/drop-example-theme-social-sharing.sass#L98-L152) and appears to be easy to extend beyond 3 elements.

3. This is a feature of `Tether` which is the library driving how the `Drop` elements are positioned. You can pass `Tether` options to `Drop` via `tetherOptions` [[Link to documentation](http://github.hubspot.com/drop/#-tetheroptions-)]. I believe you can pass `constrainToWindow: false` to keep it tethered below your element, even on scroll.
