### ISSUE TITLE
Always error, help

### ISSUE THREAD

**Issue by odirus** [HubSpot/drop#31]
When I load "Drop" after "Tether", and follow documentation, but always got error: Tether Error: Both element and target must be defined, I want to know how to defined element, thanks

**Comment by geekjuice** [comment]
Is this still an issue? I believe if you just include the `drop[.min]?.js` at the root of this project, it includes `Tether` without having to require `Tether` explicitly anymore.

**Comment by DonaldTaylor** [comment]
This is still an issue with Drop 0.5.7.

**Comment by geekjuice** [comment]
The recent updates that added UMD support should have resolved this issue. Let me know if it still persists and I'll be happy to take another look.
