### ISSUE TITLE
amd/require support

### ISSUE THREAD

**Issue by piotrpalek** [HubSpot/drop#35]
Hey, It would be really nice if drop (and tether and all of the other awesome libraries) would be available on bower/npm. Also if they would have module support (amd/require/es6) that would be really helpfull. Is it possible?

edit: Ok I see it on bower now, was searching for drop.js before. (would be a good idea to add it to the readme, how to install it via bower)

**Comment by geekjuice** [comment]
`Drop` is actually available in __Bower__ under `drop`. My guess for why it isn't published on __npm__ yet is that the name `drop` was already taken. I'll ask around and see if we rename it for __npm__ and have it published soon.

**Comment by kimmobrunfeldt** [comment]
Any update on the npm package? I would need it

**Comment by kimmobrunfeldt** [comment]
Btw, the first thing I searched from npm after "drop" was "hubspot drop"

**Comment by giladgray** [comment]
Easy workaround is to install via `git://` URL: `npm install git://github.com/hubspot/drop` or add `"drop": "git://github.com/hubspot/drop"` to your package.json.

Would still be much more convenient to simply have it published on NPM...
