### ISSUE TITLE
DOMContentLoaded - updateBodyClasses() - Error undefined 

### ISSUE THREAD

**Issue by kvey** [HubSpot/drop#36]
```
	  document.addEventListener('DOMContentLoaded', function() {
	    return Drop.updateBodyClasses();
	  });
```

If a Drop isn't instantiated before DOMContentLoaded this produces an error undefined.

**Comment by geekjuice** [comment]
I can't seem to reproduce this issue. Is this still an issue with the newest version of `Drop`? If so, could you provide some more context/examples so we can help debug the issue.

**Comment by geekjuice** [comment]
Closing for now. Let me know if you still need help.
