### ISSUE TITLE
Destroy all Drops

### ISSUE THREAD

**Issue by davidpaulsson** [HubSpot/drop#37]
Is there a simple way to destroy all drops at once? I'm using Ember and would like to clean up my view on willClearRender() .

Something like
```
willClearRender: ->
  for drop in drops
    drop.destroy()
```

Or how would one do this? Maybe I'm just overlooking something really simple.

**Comment by geekjuice** [comment]
At the moment, there is no `Drop` method that will close all drops, but you can actually access all the drops that have been created via `Drop.drops` globally. Then you can loop through each one and close them like you have above. Hopefully, we can update this library at some point and add a global `#closeAll` as that's something I've encountered as well.
