### ISSUE TITLE
How to set z-index?

### ISSUE THREAD

**Issue by dcy** [HubSpot/drop#39]
![2014-10-20-164630_462x117_scrot](https://cloud.githubusercontent.com/assets/1137238/4698537/b4893366-5835-11e4-9871-c695f7e37631.png)

.notify-panel{
    width: 300px;
    z-index: 1120;
}
the drop also shows bellow the input.
I don't want the drop shows below the input.

**Comment by geekjuice** [comment]
It seems like you can just set `z-index` on `.drop` in your stylesheets to be greater than 1120.
