### ISSUE TITLE
Events bound to document

### ISSUE THREAD

**Issue by berkin** [HubSpot/drop#43]
For every drop instance, there is an event bound to the document for handling close. I have a single page application so the bound events to the document are never removed and after a while, there will be thousands of events bound to the document.

**Comment by geekjuice** [comment]
Good catch. It seems like we could just add the `removeEventListener` on the `Drop#destroy` method [here](https://github.com/HubSpot/drop/blob/master/coffee/drop.coffee#L291-L292). Would you like to see if that works and open a pull request if it does?

**Comment by geekjuice** [comment]
Sorry for the last response. On second thought `remove` works as expected as the purpose is to remove the instance from the DOM, but not entirely. For that, you can use `destroy` which will remove the drop and all of the events attached to it. The events bound to `document` actually get cleaned up as well [here](https://github.com/HubSpot/drop/blob/master/src/js/drop.js#L402-L405). Let me know if it's still an issue though and I'll be happy to take another look.
