### ISSUE TITLE
Arrows removed if does not fit in window/container

### ISSUE THREAD

**Issue by jhaesus** [HubSpot/drop#46]
http://jsfiddle.net/eyu8rw6L/

Middle ones work ok, top and bottom ones do not display their arrows.

**Comment by geekjuice** [comment]
This is definitely something that we need to fix, but haven't had a chance to tackle. If having the arrow is more important than overflow, you could pass `constrainToScrollParent: false` which will force the `Drop` element to tether to it's target correctly regardless of whether or not the target is visible in the viewport. [Link to jsFiddle](http://jsfiddle.net/eyu8rw6L/1/).

**Comment by markalfred** [comment]
+1

**Comment by geekjuice** [comment]
Related https://github.com/HubSpot/drop/issues/16. Closing in favor of that one. Seems to be the same issue more or less.
