### ISSUE TITLE
Misplacing drop-element in Ember

### ISSUE THREAD

**Issue by lucasbeef** [HubSpot/drop#48]
Hi,

The drop will always be placed on top of the drop-target, even though you specify "bottom something" in the options.

I am using Drop in an Ember project.

After some debugging, i could see that the transcribe method gets called 2 times (not sure why) for every click on the target .The first call (right  after a page refresh) places it appropriately at the bottom of my target. Then the method is called again causing my drop to move from the bottom (the position I wanted), to the top.

If I summarize : 

-- Refresh the page, the drop is instantiated
-- 1st lick on the target
    ---- first call to transcribe, the drop is well placed
    ---- second call to transcribe, the drop align with the top of the target
Then for every click on the target, the transcribe method gets called 2 times with false Y pos so that the drop stays on top of the target.

Any clue on why this happens ?
Thanks

**Comment by geekjuice** [comment]
It's hard to debug without some code or examples, but I'm going to guess that you have a click handler to create the `Drop` instance and the event is bubbling up. Have you tried calling `event.stopPropagation()` in your handler and see if that fixes the issue? If not, a bit more context could help us debug your issue.

**Comment by geekjuice** [comment]
Closing issue. Feel free to reopen if it's still an issue.
