### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by samcov** [HubSpot/drop#5]
Is there a reason that the demo is not included in the distribution?

**Comment by milanstosic** [comment]
Yes, that definitely must be mentioned because Drop won't work without Tether and that isn't mentioned anywhere...

**Comment by milanstosic** [comment]
Hm, now I see that is mentioned on Github (in readme.md) but I was trying with instructions from a website.

**Comment by geekjuice** [comment]
@milanstosic Sorry about the confusion. We are in the process of updating all of the documentation (so the website), but first wanted to tackle updating the code in the `tether` based projects first. But yes, `Tether` must be included in your project to use `Drop`. `Tether` used to come bundled with `Drop`, but we have decided to drop the bundling (for now) in favor of providing proper UMD.

**Comment by milanstosic** [comment]
Ok, thanks.
