### ISSUE TITLE
Dependencies for drop

### ISSUE THREAD

**Issue by cprcrack** [HubSpot/drop#51]
Where can I find documentation on which files should I include for drop to work? Do I have to include all files under "js" and "css" folders for both tether and drop releases? Specially tether seems to have a lot of stuff there, likes utils.js and others. Must mention that I cannot use the minified versions because I want my app's whole code to be easily reviewed.

**Comment by geekjuice** [comment]
You can just include the `drop.js` at the root of the project. It includes `Tether` which is the only hard dependency for `Drop`. You can pick and choose which styles you want from the `css` directory though.

**Comment by cprcrack** [comment]
That's what I tried at first, but including only drop.js raised an error saying tether.js is missing, which after including raised an exception saying utils.js is missing...

**Comment by cprcrack** [comment]
Attaching a screenshot for clarity with line numbers. Using the last release 0.5.5  
![drop_error](https://cloud.githubusercontent.com/assets/650925/6046037/de5d6938-ac9e-11e4-9f80-22f2c2dd40ab.png)

**Comment by cprcrack** [comment]
Oh fuck, there's another drop.js file right in the root folder, I was using the one in the js folder.

**Comment by geekjuice** [comment]
haha simple mistake. :sweat_smile:
