### ISSUE TITLE
Programmatically disable drop?

### ISSUE THREAD

**Issue by etcook** [HubSpot/drop#52]
Is there any way to programmatically disable drop? I'd like to allow the drop to be activated only in certain circumstances.

Thanks!

**Comment by geekjuice** [comment]
Sorry for the delay. Have you considered using `openOn: null`? If so you can do stuff like:

```javascript
let drop = new Drop({
    target: document.querySelector('.drop-target'),
    content: 'Some content',
    openOn: null
});

if (someCondition) {
    drop.open();
} 

if (someOtherCondition) {
    drop.close();
}
```

Let me know if that works for you and if it doesn't, feel free to reopen this issue.
