### ISSUE TITLE
Only add my custom classes to the drop-element and not the target?

### ISSUE THREAD

**Issue by aaronmw** [HubSpot/drop#53]
When I pass in custom classes to Drop, it applies those classes to BOTH the target and the drop element. Now, if I wanted those on the target, I'd add them myself. But since Drop creates the drop container itself, I get why it'd accept custom classes.

Is there some way to suppress the addition of my classes onto the target, too? I'm adding like `emailCompositionWindow` to the drop element, which sets up widths and stuff, and those same classes are being applied to the button. I'm also adding `js-email-composition-window` which is for testing, and now I've got two elements in my DOM with those classes, which breaks tests :(

Any help would be hugely appreciated!

Thanks!

**Comment by geekjuice** [comment]
Just out of curiosity, but any reason you couldn't style and query drop element with something the `.drop` prefix like:

```css
.drop.emailCompositionWindow {
    // styles...
}
```

or 

```javascript
dropElement = document.querySelector('.drop.emailCompositionWindow');
```

Basically you can query for the specific drop element as opposed to the target element by checking for the addition of the `drop` class. If this doesn't seem viable, feel free to let me know what the specific use case might be where this wouldn't work and I'll help figure out a solution for this. :smile:

**Comment by aaronmw** [comment]
Yeah, I'm doing that instead now. The tests are what were tripping me up, but I can just doctor them to do the same. Just need to make sure it's clear why I'm over qualifying the selectors so future tests don't break. Probably not worth any mods to the library. 

Thanks for the response! This'll get me far enough :)

**Comment by geekjuice** [comment]
Awesome! :smile: Yea, I thinking increasing the specificity should be fine, even for future iterations. I can't imagine that changing in the future, at least without a major new release announcement. 

Thanks again for using `Drop` and definitely feel free to let us know if you need any help or guidance in using the library! :tada:

**Comment by vlkosinov** [comment]
Wow. This behavior is destructing, especially when we are using css modules. @geekjuice are there any solutions for this problem?
