### ISSUE TITLE
Usage of calc() isn't very cross-browser

### ISSUE THREAD

**Issue by kimmobrunfeldt** [HubSpot/drop#54]
Hi,

I like drop but I wouldn't say that it supports "IE9+ and all modern browsers". 

Looking at http://caniuse.com/#feat=calc it seems calc has a lot of bugs in many IE versions. Android support seems to be quite poor and Opera Mini does not support the feature at all.

**Comment by NicBright** [comment]
According to http://caniuse.com/#feat=calc, the only problem in IE9 is when using calc() in combination with background-position. As the bounce-themes use calc within the "transform-origin" property, maybe it is not a problem? 

Concerning Android support: all browsers except Opera Mini support the calc() feature according to http://caniuse.com/#feat=calc ...

Regarding Opera Mini I personally consider this browser's primary use-case to be for consuming content oriented web pages (like news), and not so much for using it in interactive apps (where you really need Drop.js). In the end, what Opera Mini does is saving bandwidth which comes at a cost: for example limited JavaScript support and no animations: https://dev.opera.com/articles/opera-mini-content-authoring-guidelines/#html-css-support -- I personally think it's not worth the effort of trying to get Drop (or tether) to work with Opera Mini.

**Comment by geekjuice** [comment]
For the most part, we haven't found too many issues when tested against IE9+ and modern browsers. If you happen to find specific issues though that are possibly caused by `calc`, feel free to open a new issue and I'll be more than happy.
