### ISSUE TITLE
Right click support

### ISSUE THREAD

**Issue by stevenh77** [HubSpot/drop#56]
Great project guys!  Any plans to support right click functionality?  

We've written a wrapper for Angular and would love to add right click support:
https://github.com/stevenh77/drop-ng

**Comment by geekjuice** [comment]
Awesome! It's always great to see `Drop` being integrated into other projects.

And in regards to your question, do you mean having an option to open a `Drop` instance via right-click e.g. `openOn: 'right-click'`? If so, we can definitely consider it, but I've always been wary of overriding right-click functionality.

In the meantime, you could consider adding a `contextmenu` event listener to your element and opening a `Drop` instance in the handler:

```javascript
var el = document.querySelector('.drop-target'),
      drop;
el.addEventListener('contextmenu', function(event) {
    e.preventDefault()
    if (typeof drop !== 'undefined') {
        drop.open()
    } else {
        (drop = new Drop({
            target: event.currentTarget,
            content: '<div>Look, right-clicked Drop!</div>',
            position: 'top center'
        })).open()
    }
})
```

Of course YMMV (and I'm not too familiar with Angular directive) so you may need for a `right-click` option for `openOn`. If that is case, I'll take note, ask the team here about their thoughts of `right-click`, and definitely get back to you. :smile:

**Comment by stevenh77** [comment]
Thanks Nicholas for such a speedy and detailed response!  

I'd managed to get the drop opening on right click within my directive using similar code to yours above.  The issue I had was either disabling left click opening the drop or in my case where I set the openOn to say 'rightclick', which prevents a click opening the drop and requires manual code to open, how I then manually close the drop.

Any suggestions?

**Comment by geekjuice** [comment]
So after playing around with this, I can see why having an `openOn: 'rightclick'` would be convenient, but may introduce a lot more complexity trying to handle click events properly.

This probably isn't the best solution, but here's one example of how you could bind a target to open on `right-click`, allow for the contents to be `left-click`-able, and close on `left-click` anywhere else in the document. [Fiddle](http://jsfiddle.net/2v7fq21k/4/)

Not sure if that answers your question, so I'll be more than happy continue helping out if needed. :smile:

**Comment by stevenh77** [comment]
Nice one, I'll give that a go!

**Comment by stevenh77** [comment]
Got it working, thanks for your help!

Here's an example:  http://stevenhollidge.com/drop-ng/example/rightclick/rightclick-close.html

Let me know if you do end up supporting right click and I'll take out my hack :smile:

**Comment by geekjuice** [comment]
Awesome! :+1: And if we do end up doing that, we'll mention you in the commit/release :smile_cat:
