### ISSUE TITLE
Drop with requirejs

### ISSUE THREAD

**Issue by ditoglez** [HubSpot/drop#59]
Hi!
I am trying to use drop with require.js. As far as I see, the drop element doesn't reposition itself on window resize or scroll event. Using it straight without require.js everything works fine.

Sample code:

```javascript
require.config({
    baseUrl: './',
    paths: {
        'TetherUtils': 'bower_components/tether/js/utils',
        'Tether': 'bower_components/tether/js/tether',
        'Drop': 'bower_components/drop/js/drop'
    },
    shim: {
        'TetherUtils': {
            'exports': 'TetherUtils'
        },
        'Tether': {
            'exports': 'Tether',
            'deps': ['TetherUtils']
        },
        'Drop': {
            'exports': 'Drop',
            'deps': ['Tether']
        }
    }
});

require(['Drop'], function (Drop) {

   var drop =  new Drop({
        target: document.querySelector('.button'),
        content: '<div class="__drop__element">DROP ELEMENT</div>',
        placement: 'bottom center',
       constrainToWindow: true,
        openOn: 'click'
    });
});

**Comment by geekjuice** [comment]
Thanks for using `Drop`!. I recently pushed out some big changes to support UMD modules. Let us know if you still run into any issues with the new version of `Drop`, but hopefully it should now have `Require.JS` support :smiley_cat:

**Comment by ivadenis** [comment]
I'm having difficulties with `requirejs` and `drop` setup. It seems that instance is returned from from module, rather than an object itself. Is it intended? While using AMD, how would I set context for a particular instance?
