### ISSUE TITLE
Always fit within viewport, in secondary dimension?

### ISSUE THREAD

**Issue by henrik** [HubSpot/drop#60]
If a Drop.js is set to appear *below* an element, the `constrainToWindow: true` option will make it appear *above* the element instead if necessary to fit inside the viewport.

But if the horisontal center of the anchor point of the Drop is close to the left or right edge of the window, it may go outside the window horisontally as seen here:

![](https://cloud.githubusercontent.com/assets/216/7111109/a61bc8d8-e1bb-11e4-8990-2900c7e54ecd.png)

Is there any built-in way to fix that issue? Ideally I think it would shift the content to fit the viewport width, but the arrow would stay put, becoming off-centered.

**Comment by NicBright** [comment]
You can improve the behaviour a little bit with these tetherOptions (if you give constraints in this way, constrainToWindow and constrainToScrollParent will be completely ignored, because the constraints they produce are overwritten)

        tetherOptions: {
            constraints: [{
                to: 'window',
                pin: true,
                attachment: 'together'
            }]
        }

**Comment by henrik** [comment]
@NicBright Oh, excellent! Thank you so much.

**Comment by geekjuice** [comment]
Seems like a solved issue :+1: If not, feel free to reopen the issue.

**Comment by henrik** [comment]
Yeah, you can probably consider it solved. Would be nice if it had this behavior by default (you probably never want it to *not* fit within the viewport), but maybe that's tricky.

**Comment by geekjuice** [comment]
@henrik Actually, there is a potential fix for this coming soon via https://github.com/HubSpot/tether/pull/81. Is this closer to the type of solution you were looking for where it stays in the viewport?

**Comment by henrik** [comment]
@geekjuice Yup, that looks like exactly what I was after!

**Comment by yairEO** [comment]
what fix? there's an "ugly horizontal scrollbar" as @NicBright described. it's a huge show-stopper

**Comment by geekjuice** [comment]
I think the example in https://github.com/HubSpot/tether/pull/81 has scroll bars to demonstrate the attachment position adjusting to being close to the edges and repositioning to stay within the view port. In practice, you shouldn't see scroll bars as the entire point is keep the tethered content in the viewport.
