### ISSUE TITLE
allow options.content to be a function returning an element (not HTML string) called on each open

### ISSUE THREAD

**Issue by adidahiya** [HubSpot/drop#61]
Similar to https://github.com/HubSpot/drop/commit/195fa0e3f45ca5a3774423abbce483d6ce519cef, I'd like the option to supply Drop with a content-generating function that returns an `HTMLElement` (rather than a `string` that is assigned to `@content.innerHTML`). The main advantage I hope to gain here is that event handlers & other data on the original content element will be preserved when passed to Drop.

**Comment by b-ash** [comment]
Seems reasonable. I'm happy to look at a PR if you want to whip something up.

**Comment by adidahiya** [comment]
cool, see #63
