### ISSUE TITLE
Events (open|close)

### ISSUE THREAD

**Issue by Cristiian** [HubSpot/drop#62]
Is there a way to fire an event when the Dropdown is shown?, I read the documentation, but still is not clear.
I tried using 'on' this but is not working:
on(eventName, handler, [ctx])

![captura de pantalla 2015-04-18 16 05 19](https://cloud.githubusercontent.com/assets/5752018/7217270/dbe29e42-e5e4-11e4-8211-4d2c61ce7ec8.png)

**Comment by lincolndbryant** [comment]
`on` and `off` are meant to be used on the instance rather than in the configuration object.
```
drop = new Drop()
drop.on('open', function() { ... })
```
http://github.hubspot.com/drop/#events
