### ISSUE TITLE
Make Tether be a devDependency instead of a dependency

### ISSUE THREAD

**Issue by NicBright** [HubSpot/drop#66]
Hi there,

as Drop.js concatenates the Tether library to create a standalone library file (drop.min.js), we should move (in bower.json) the Tether dependency from "dependencies" to "devDependencies".

**These are the advantages:**

1. people that only include Drop.js as a dependency in their projects won't have to download Tether as well. This is especially important in cases where the CI servers are configured not to preserve the bower_components folder, but to checkout all dependencies from scratch in each run (even if it uses a cache). 
2. people who just want to include `bower_components/**/*.min.js` won't have to explicitly exclude tether.min.js. This is especially important as Drop.js still works when not excluding tether.min.js explicitly. What's really bad in this situation is, that all tether modules are registered twice, slowing down all tether related positioning stuff by a factor of 2.

**Yet even better solution:**
Leave Tether as a dependency and rewrite Drop.js to NOT include tether itself, but to make use of whatever Tether library is already included in the page. This allows people to be more flexible, e.g. they can decide to use a patched version of Tether, without having to dig into the CoffeScript-compiled version that ships with Drop.js.

**Comment by geekjuice** [comment]
Hi again! The recent update actually makes `Tether` a separate dependency since we decided to no longer bundle (or concat in this case) `Tether` with `Drop`. Hopefully the changes reflect your __better solution__ as we feel this is a much better solution as well. Again feel free to let me know if you have any issues :smile_cat:
