### ISSUE TITLE
Update versions in bower.json and package.json

### ISSUE THREAD

**Issue by NicBright** [HubSpot/drop#67]
When i got a new version of Drop.js recently (through `bower update`), I was very confused that package.json and bower.json did not reflect this version number. They're not even the same (package.json has 0.5.4 and bower.json states 0.5.5 while Drop.js is (per git tag) on 0.5.7).

**Comment by geekjuice** [comment]
Thanks for using `drop` and providing feedback :smile_cat: I recently pushed out some major changes that updates both `bower.json` and `package.json` to reflect the correct version numbers. One difference is that you may have to install then as `tether-drop` now as all `Tether`-based projects will now be prefixed with `tether` (mainly to stay unique). Feel free to let me know if you have any issues and I'll be more than happy to help out.
