### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by jonathansimmons** [HubSpot/drop#80]
I'm getting an `addEventListener` error when I try to use drop in via coffee script with a rails project.Here is the setup:

**application.js**
```js
//= require jquery
//= require jquery_ujs
//= require jquery.turbolinks
//= require turbolinks
//= require hubspot/tether.min.js
//= require hubspot/drop.min.js
//= require moment.min.js
//= require_tree .
//= require_self
```

**accounts.js.coffee** which is included by the `//= require_tree .` line

```js
accountSwicher = new Drop
  target: document.querySelector('.account-switcher')
  content: 'Welcome to the future!'
  position: 'bottom left'
  openOn: 'click'
```

The resulting js that is render in the browser is:
```js
(function() {
  var accountSwicher;

  accountSwicher = new Drop({
    target: document.querySelector('.account-switcher'),
    content: 'Welcome to the future!',
    position: 'bottom left',
    openOn: 'click'
  });

}).call(this);
```

But when the page loads I get: 
`Uncaught TypeError: Cannot read property 'addEventListener' of null`
which is throwing an error on [this line](https://github.com/HubSpot/drop/blob/945fff030f8f998faf4cc8b30d719ffbcfaa5bca/dist/js/drop.js#L189)

The weird thing is that if I just take the resulting js above, and include it directly in a js file, commenting out the contents of `accounts.js.coffee` to take it out of the picture, everything works fine. 

Any thoughts here?

**Comment by geekjuice** [comment]
Hmm, that's strange. It seems like the element isn't on the DOM when `accounts.js.coffee` is being executed. Are you waiting for the `DOMContentLoaded` or the DOM `ready` event before trying to create the Drop?

**Comment by jonathansimmons** [comment]
Haha that was it. I feel so dumb. 

Some questions you just want to delete from the universe, this is one of them. That is what I get for coding after only sleeping 2 hours.

**Comment by geekjuice** [comment]
No worries. Happens to the best of us :sweat_smile:
