### ISSUE TITLE
releases vs. tags?

### ISSUE THREAD

**Issue by jjb** [HubSpot/drop#81]
I don't know the workflow for this but it seems that there haven't been releases made for the recent point release tags. https://github.com/HubSpot/drop/releases

![releases_ _hubspot_drop](https://cloud.githubusercontent.com/assets/6097/7942363/be40f2c0-092b-11e5-8f18-4ddf5148010c.png)

**Comment by geekjuice** [comment]
Correct me if I'm wrong, but a release is basically a glorified git tag, no? I know that we can edit tags under `Releases` to include more detail like the `Major updates` release, but other than that, I was under the impression they were the same thing.

That said, we are working to be more diligent about maintaining these projects, so haven't quite built the habit of updating everything - git tag, npm, bower, changelog, release - quite yet.

**Comment by jjb** [comment]
I have never used Releases myself, I just noticed that there were point-release tags that were "collapsed" and that maybe that wasn't intentional. Feel free to ignore my observation :)

**Comment by geekjuice** [comment]
No worries :smile_cat: I've actually started to create releases as the `hub` CLI pushes the tag when creating a release.

**Comment by jjb** [comment]
:cool:
