### ISSUE TITLE
transitionEndEvent is always evaluated to 'transitionend'

### ISSUE THREAD

**Issue by dwchMikael** [HubSpot/drop#83]
In the code that tries to find which transitionend event shouldn't
if (tempEl.style[_name] !== 'undefined') {
be
if (tempEl.style[_name] !== undefined) {

That is, test against undefined and not the string 'undefined'.

**Comment by dwchMikael** [comment]
Sweet, my bad for not running the latest version.

**Comment by geekjuice** [comment]
No problem. Thanks for catching that typo :+1:
