### ISSUE TITLE
Drop.close() sometimes leaks transitionend listeners

### ISSUE THREAD

**Issue by dwchMikael** [HubSpot/drop#84]
Look at the example usages of Drop at http://github.hubspot.com/drop/docs/welcome/ . Scroll down to the "The Popover"-example, and open and close the "About Drop.js" popover several times. Looking at the timeline profiling in chrome, it seems like the drop.close() method is adding an event listener for transitionend but it is never removed, ie the event handler is never triggered.

Is this a configuration/usage issue or a memory leak?

**Comment by geekjuice** [comment]
Hmm, I'm not seeing that behavior. Even looking at the events attached to the `drop` instance using `getEventListeners`, I don't the event stacking for `transitionend`. 

Do you mind taking another look and/or creating a jsFiddle using the latest version of the library to see if the issue still persists?

**Comment by dwchMikael** [comment]
Yeah, I'll try to reproduce in jsfiddle. Thanks for the response.

**Comment by dwchMikael** [comment]
Here is a jsFiddle that reproduces what I am seeing. https://jsfiddle.net/u6pm3ka4/4/

Press the open button, then the close button.
Repeat open and close (mod three times).
On the third time it closes the drop instance a "`debugger;`" statement is hit. At this time I can run `getEventListeners(dropInstance.drop)` in the console and get the following result:
`Object {transitionend: Array[3]}`.

Any thoughts would be appreciated.

With Regards
Mikael

**Comment by geekjuice** [comment]
Ah... okay I see what's going on. The `close` method only cleans up the transitions when you use a theme that uses CSS transitions [example](https://jsfiddle.net/u6pm3ka4/6/). In the example you provided , the theme has no transitions, so the `transitionend` event will never be triggered and the event listener will never be cleaned up. I'll look into how we can fix that since it's hard to determine whether a correct theme is applied that uses transitions in the first place.

**Comment by dwchMikael** [comment]
Thanks for confirming. And thanks for responding so quickly.

As a temporary workaround we can just locally comment out the registering of the event listener, as we know we don't have any transitions in our drop styles.

Please let me know if there is anything we (co-workers and I) can do to help.

**Comment by geekjuice** [comment]
Updated the [fiddle](https://jsfiddle.net/u6pm3ka4/7/) using the file from https://github.com/HubSpot/drop/issues/86. It you look at the output of `getEventListeners`, it should be an empty object since no events were added to begin with.

**Comment by dwchMikael** [comment]
Yeah, the patch works.

I think one of the alternative solutions you could consider is to place the `transitionend` event listener on the dropInstance itself instead of having it as a local variable in `close()`. Something like  `dropInstance._transitionEndHandler = ...`. This would prevent the stacking as well, since all the listeners would be identical and therefore any additional calls to addEventListener would be discarded (see https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Multiple_identical_event_listeners). This way there isn't a need to check the style for transitions.

And having one "stacking" listener per dropInstance isn't a problem. Especially since it is eventually cleaned up after you call `dropInstance.destroy()` and clear references to the dropInstance.

**Comment by dwchMikael** [comment]
Ops, spoke too soon. The patch works in chrome, but not in IE, which ofc has another default transition style.
