### ISSUE TITLE
v1.1.1 incorrectly tagged

### ISSUE THREAD

**Issue by canterberry** [HubSpot/drop#85]
The **bower.json** file on the `v1.1.1` tag still references its version as `1.1.0`. This is causing a **mismatch** warning when performing a `bower install`:

> ```
> bower not-cached    git://github.com/HubSpot/drop.git#~1.1.1
> bower resolve       git://github.com/HubSpot/drop.git#~1.1.1
> bower download      https://github.com/HubSpot/drop/archive/v1.1.1.tar.gz
> bower extract       tether-drop#~1.1.1 archive.tar.gz
> bower mismatch      Version declared in the json (1.1.0) is different than the resolved one (1.1.1)
> bower resolved      git://github.com/HubSpot/drop.git#1.1.1
> bower install       tether-drop#1.1.1
> 
> tether-drop#1.1.1 bower_components/tether-drop
> └── tether#1.0.2
> ```

**Comment by geekjuice** [comment]
Should be fixed
