### ISSUE TITLE
undefined is not an object (evaluating 'Tether.Utils')

### ISSUE THREAD

**Issue by idmean** [HubSpot/drop#87]
I get the following error with any of 1.x versions in Safari. Here 1.1.0:

    [Error] TypeError: undefined is not an object (evaluating 'Tether.Utils')
	(anonymous function) (drop.js, line 29)
	(anonymous function) (drop.js, line 9)
	global code (drop.js, line 11)

This error occurs when I load the file, it is likely not related to any other code.

**Comment by idmean** [comment]
Okay, my fault. I forgot to load Tether.js.

However you probably should make that more clear in your docs:

>Dependencies

>None!

and 

>Then add this to your page:

>     <link rel="stylesheet" href="drop-theme-arrows.css" />
>     <script src="drop.min.js"></script>

**Comment by geekjuice** [comment]
Yea, we're in the middle of updating how we generate docs, so in the meantime, the `README.md` in this repo contains the most up to date info. The docs should include that information soon though!
