### ISSUE TITLE
Tag for tag v1.1.2 and tag v.1.1.1 references the same changeset

### ISSUE THREAD

**Issue by dwchMikael** [HubSpot/drop#88]
Hi,

Both v1.1.1 and v.1.1.2 both references the changeset 892a800c7df1a4a867dfaf7edd5b1c5aed54fb04.
Currently unable to get the fix for the stacking transitionend listeners via bower.
Could you please make a release containing the latest changes.

With Regards
Mikael

**Comment by geekjuice** [comment]
Should be fixed. :+1:
